using Microsoft.Extensions.Logging;

namespace AgentCore.AspNetCore.Call;

/// <summary>The lines the call route writes while the host starts.</summary>
/// <remarks>
/// Source-generated by <see cref="LoggerMessageAttribute"/>, as CA1848 asks. Silently leaving a
/// route unmapped is how a deployment loses every call to a 404 with nothing to read, so each
/// reason says so once.
/// </remarks>
internal static partial class CallRouteLog
{
    /// <summary>The host registered no call adapter, or loaded no document.</summary>
    /// <param name="logger">The logger of the map-time gate, not of any call.</param>
    /// <param name="pattern">The route this host asked for and did not get.</param>
    /// <param name="reason">What was missing, in the words a reader can act on.</param>
    [LoggerMessage(
        EventId = 1,
        Level = LogLevel.Information,
        Message = "the call route '{Pattern}' is not mapped: {Reason}.")]
    public static partial void RouteNotMapped(ILogger logger, string pattern, string reason);

    /// <summary>The document named a vendor this process dials out to, which owns no route.</summary>
    /// <param name="logger">The logger of the map-time gate, not of any call.</param>
    /// <param name="kind">The <c>providers.call.kind</c> the document named.</param>
    /// <param name="pattern">The route this host asked for and did not get.</param>
    [LoggerMessage(
        EventId = 2,
        Level = LogLevel.Information,
        Message = "providers.call names '{Kind}', which this process dials out to rather than "
            + "being dialled in to, so the call route '{Pattern}' is not mapped.")]
    public static partial void DialOutVendorMapsNoRoute(ILogger logger, string kind, string pattern);
}
