using Microsoft.Extensions.Logging;

namespace AgentCore.AspNetCore.Vendors.TelnyxRelay;

/// <summary>
/// Every line the relay connection writes.
/// </summary>
/// <remarks>
/// <para>
/// The methods are source-generated by <see cref="LoggerMessageAttribute"/>, so a line that nobody
/// listens to costs one level check and allocates nothing. CA1848 asks for exactly this shape
/// rather than a direct call on <see cref="ILogger"/>.
/// </para>
/// <para>
/// No line here carries what the caller said or pressed. The audit chain of D23 is the record of a
/// call, and a log is not; a keypad in particular carries card numbers, PINs, and dates of birth.
/// </para>
/// </remarks>
internal static partial class TelnyxRelayLog
{
    /// <summary>Section 3.1. An unmodelled frame type, logged once for the call.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="frameType">The <c>type</c> value no case matched.</param>
    /// <param name="callId">The id of the call, or a placeholder before setup.</param>
    [LoggerMessage(
        EventId = 1,
        Level = LogLevel.Information,
        Message = "the relay sent an unmodelled frame type '{FrameType}' on call {CallId}.")]
    public static partial void UnknownFrameType(ILogger logger, string frameType, string callId);

    /// <summary>The caller pressed one key. The key itself never reaches a log line.</summary>
    /// <param name="logger">The logger of the connection.</param>
    [LoggerMessage(
        EventId = 2,
        Level = LogLevel.Information,
        Message = "the caller pressed a key.")]
    public static partial void DtmfReceived(ILogger logger);

    /// <summary>The vendor refused a frame this endpoint sent. That is our defect.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call, or a placeholder before setup.</param>
    /// <param name="description">Why the vendor refused it.</param>
    [LoggerMessage(
        EventId = 3,
        Level = LogLevel.Warning,
        Message = "the relay refused a frame on call {CallId}: {Description}")]
    public static partial void FrameRefused(ILogger logger, string callId, string description);

    /// <summary>A prompt arrived before any setup frame, logged once for the call.</summary>
    /// <param name="logger">The logger of the connection.</param>
    [LoggerMessage(
        EventId = 4,
        Level = LogLevel.Warning,
        Message = "the relay sent a prompt before any setup frame. Every prompt before setup is dropped.")]
    public static partial void PromptBeforeSetup(ILogger logger);

    /// <summary>The read loop ended in a fault rather than a clean close.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call, or a placeholder before setup.</param>
    /// <param name="exception">The cause.</param>
    /// <remarks>
    /// <see cref="Application.Diagnostics.Log"/> states the house rule: on a voice call, silence is
    /// the failure, so this line makes sure a read loop fault is never silent. It fires for anything
    /// the read loop throws other than the two causes that have their own, quieter case: a
    /// <see cref="RelayProtocolException"/> logs through <see cref="RelayProtocolViolation"/> at
    /// Warning instead, because it is a protocol violation this endpoint already refused and closed
    /// on, not an unhandled defect; and a dropped socket with no close frame logs through
    /// <see cref="CallDroppedWithNoCloseFrame"/> at Information. Everything else reaching this line
    /// is this endpoint's own bug.
    /// </remarks>
    [LoggerMessage(
        EventId = 5,
        Level = LogLevel.Error,
        Message = "the relay read loop of call {CallId} ended in a fault.")]
    public static partial void ReadLoopFaulted(ILogger logger, string callId, Exception exception);

    /// <summary>A turn faulted rather than finishing or being cancelled by the connection itself.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call.</param>
    /// <param name="exception">The cause.</param>
    [LoggerMessage(
        EventId = 6,
        Level = LogLevel.Error,
        Message = "a turn of call {CallId} faulted.")]
    public static partial void TurnFaulted(ILogger logger, string callId, Exception exception);

    /// <summary>The write loop ended in a fault rather than a clean close.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call, or a placeholder before setup.</param>
    /// <param name="exception">The cause.</param>
    /// <remarks>
    /// The write loop is the only task that touches the socket, so its fault — typically a
    /// <see cref="System.Net.WebSockets.WebSocketException"/> the relay caused, or an
    /// <see cref="ObjectDisposedException"/> racing teardown — is the most useful of the three to
    /// see, and the one round 1 left unobserved.
    /// </remarks>
    [LoggerMessage(
        EventId = 7,
        Level = LogLevel.Error,
        Message = "the relay write loop of call {CallId} ended in a fault.")]
    public static partial void WriteLoopFaulted(ILogger logger, string callId, Exception exception);

    /// <summary>A bounded teardown wait expired before the task it was watching stopped.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call.</param>
    /// <param name="what">Which task did not stop in time, for example "the last turn".</param>
    /// <remarks>
    /// Cancellation reaches a well-behaved task, but this line is not proof of one that ignored its
    /// token — a task that honours cancellation yet takes longer than <c>CloseTimeout</c> to unwind,
    /// a slow completion step or a slow sink, reaches it the same way. Left unbounded, either case
    /// would otherwise wedge teardown forever: the session would stay in the store, and the Kestrel
    /// request behind it would never complete.
    /// </remarks>
    [LoggerMessage(
        EventId = 8,
        Level = LogLevel.Error,
        Message = "{What} of call {CallId} did not stop before the close timeout.")]
    public static partial void TeardownTimedOut(ILogger logger, string callId, string what);

    /// <summary>The close handshake faulted for a reason other than its own deadline or a dead peer.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call, or a placeholder before setup.</param>
    /// <param name="exception">The cause.</param>
    /// <remarks>
    /// Logged and swallowed rather than left to propagate, because a throw here must not skip the
    /// write-loop observation or the session removal that follow it in <c>RunAsync</c>.
    /// <see cref="Sessions.InMemoryCallSessionStore"/> documents that it evicts nothing on its own,
    /// so a session removal that never runs lives for the rest of the process.
    /// </remarks>
    [LoggerMessage(
        EventId = 9,
        Level = LogLevel.Error,
        Message = "the close handshake of call {CallId} faulted.")]
    public static partial void CloseFaulted(ILogger logger, string callId, Exception exception);

    /// <summary>Cancelling the connection's own token faulted, from a registered callback.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call, or a placeholder before setup.</param>
    /// <param name="exception">The cause.</param>
    /// <remarks>
    /// Logged and swallowed rather than left to propagate, because <c>Cancel()</c> runs with
    /// <c>throwOnFirstException: false</c>: every callback still ran and both loops are already
    /// cancelled by the time this fires, so the only thing a throw here would still cost is the
    /// rest of teardown — the write-loop observation, the close, and the session removal.
    /// </remarks>
    [LoggerMessage(
        EventId = 10,
        Level = LogLevel.Error,
        Message = "cancelling the connection token of call {CallId} faulted.")]
    public static partial void CancellationFaulted(ILogger logger, string callId, Exception exception);

    /// <summary>A third final prompt arrived while one turn ran, logged once for the call.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call.</param>
    /// <remarks>
    /// Item 6a of section 11 holds one pending prompt so a caller's second sentence is not lost.
    /// A third would queue a prompt behind a question the caller has already moved past, so it is
    /// dropped, and this line says so without repeating the words dropped.
    /// </remarks>
    [LoggerMessage(
        EventId = 11,
        Level = LogLevel.Information,
        Message = "a further prompt arrived on call {CallId} while one turn was already held. It is dropped.")]
    public static partial void PendingPromptDropped(ILogger logger, string callId);

    /// <summary>The relay reported a barge-in. Never the words the caller said.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call.</param>
    [LoggerMessage(
        EventId = 12,
        Level = LogLevel.Information,
        Message = "the relay reported a barge-in on call {CallId}.")]
    public static partial void InterruptReceived(ILogger logger, string callId);

    /// <summary>A malformed interrupt frame was refused. Section 7.1: a bad frame must not drop the call.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call.</param>
    /// <remarks>
    /// Fires when <c>utteranceUntilInterrupt</c> is missing or <c>durationUntilInterruptMs</c> is
    /// negative, logged once for the call the same way an unmodelled frame type is.
    /// </remarks>
    [LoggerMessage(
        EventId = 13,
        Level = LogLevel.Warning,
        Message = "the relay sent a malformed interrupt frame on call {CallId}. It is dropped.")]
    public static partial void MalformedInterruptFrame(ILogger logger, string callId);

    /// <summary>A second final prompt arrived while one turn ran, and is held for when it ends.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call.</param>
    [LoggerMessage(
        EventId = 14,
        Level = LogLevel.Information,
        Message = "a further prompt arrived on call {CallId} while one turn ran. It is held.")]
    public static partial void PromptHeld(ILogger logger, string callId);

    /// <summary>The relay dropped the socket with no close frame. Task 7: an ordinary end of a call.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call, or a placeholder before setup.</param>
    /// <remarks>
    /// Fires instead of <see cref="ReadLoopFaulted"/> for exactly one cause: a
    /// <see cref="System.Net.WebSockets.WebSocketException"/> whose code is
    /// <see cref="System.Net.WebSockets.WebSocketError.ConnectionClosedPrematurely"/>. The vendor
    /// never reconnects, so this is a finished call, not a defect this endpoint owns.
    /// </remarks>
    [LoggerMessage(
        EventId = 15,
        Level = LogLevel.Information,
        Message = "call {CallId} ended without a close frame from the relay.")]
    public static partial void CallDroppedWithNoCloseFrame(ILogger logger, string callId);

    /// <summary>The read loop refused a frame and the connection is closing because of it.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call, or a placeholder before setup.</param>
    /// <param name="reason">
    /// The fixed, vendor-free message <see cref="RelayProtocolException"/> carries — never the
    /// bytes the relay actually sent.
    /// </param>
    /// <remarks>
    /// Malformed JSON and an oversized frame both reach here. Neither is this endpoint's own
    /// defect — the relay broke the contract, this endpoint already refused the frame, and
    /// <c>DetermineCloseStatus</c> already carries the right close status from the same exception —
    /// so this logs at Warning, the same level <see cref="PromptBeforeSetup"/>,
    /// <see cref="FrameRefused"/>, and <see cref="MalformedInterruptFrame"/> already use for a bad
    /// frame, not at the Error level <see cref="ReadLoopFaulted"/> uses for this endpoint's own bug.
    /// </remarks>
    [LoggerMessage(
        EventId = 16,
        Level = LogLevel.Warning,
        Message = "the relay read loop of call {CallId} closed the socket over a protocol violation: {Reason}")]
    public static partial void RelayProtocolViolation(ILogger logger, string callId, string reason);

    /// <summary>No inbound frame arrived within <c>IdleTimeout</c>. Task 8: an ordinary end of a call.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call, or a placeholder before setup.</param>
    /// <remarks>
    /// The vendor never reconnects, so a silent socket is a call that is already over, not a fault
    /// this endpoint owns. This fires only when the idle deadline itself is the cause: the read
    /// loop checks that the connection's own teardown token has not also fired before it logs this
    /// line, so a socket closed for some other reason never gets this one instead.
    /// </remarks>
    [LoggerMessage(
        EventId = 17,
        Level = LogLevel.Information,
        Message = "call {CallId} ended: no inbound frame arrived before the idle deadline.")]
    public static partial void IdleTimeoutReached(ILogger logger, string callId);

    /// <summary>A frame of a known type carried a field that would not bind, logged once for the call.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="frameType">The <c>type</c> value whose body was refused.</param>
    /// <param name="callId">The id of the call, or a placeholder before setup.</param>
    /// <remarks>
    /// Section 7.1 gives a vendor that adds a frame and a vendor that changes one the same rule:
    /// neither may drop a call. A decimal <c>durationUntilInterruptMs</c> and a non-string value in
    /// <c>customParameters</c> both reach here. This is the vendor's defect and not this endpoint's,
    /// so it logs at Warning, beside <see cref="PromptBeforeSetup"/> and
    /// <see cref="MalformedInterruptFrame"/>, and never at the Error level a bug of ours gets. The
    /// field that would not bind is not named: a value the vendor sent may carry what the caller
    /// said.
    /// </remarks>
    [LoggerMessage(
        EventId = 18,
        Level = LogLevel.Warning,
        Message = "the relay sent a '{FrameType}' frame on call {CallId} whose body this build cannot "
            + "read. It is dropped, and the call continues.")]
    public static partial void FrameBodyRefused(ILogger logger, string frameType, string callId);

    /// <summary>A second setup frame arrived on one socket, logged once for the call.</summary>
    /// <param name="logger">The logger of the connection.</param>
    /// <param name="callId">The id of the call the first setup frame started.</param>
    /// <remarks>
    /// One socket carries one call, and the vendor sends one <c>setup</c>. A second one is the
    /// vendor's defect, and section 7.1 forbids dropping a call over one, so the frame replaces the
    /// session rather than refusing the socket. The first session is removed from the store as it
    /// goes: <see cref="Sessions.InMemoryCallSessionStore"/> evicts nothing on its own, and teardown
    /// only ever removes the session the connection currently holds.
    /// </remarks>
    [LoggerMessage(
        EventId = 19,
        Level = LogLevel.Warning,
        Message = "the relay sent a second setup frame on call {CallId}. The first session is "
            + "released and the new one replaces it.")]
    public static partial void SecondSetupFrame(ILogger logger, string callId);
}
