using Microsoft.Extensions.Logging;

namespace AgentCore.Infrastructure.Tools.Mcp;

/// <summary>
/// Every line an MCP session writes.
/// </summary>
/// <remarks>
/// Source-generated by <see cref="LoggerMessageAttribute"/>, so a line nobody listens to costs one
/// level check and allocates nothing. No line carries a header value or an environment value: those
/// are the credentials the document went to the trouble of keeping out of <c>command:</c>.
/// </remarks>
internal static partial class McpLog
{
    /// <summary>One connection attempt failed and another is coming.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="server">The <c>mcp:</c> id.</param>
    /// <param name="attempt">The one-based attempt that just failed.</param>
    /// <param name="attempts">How many attempts there are in total.</param>
    /// <param name="backoffMs">The wait before the next attempt.</param>
    /// <param name="error">What went wrong.</param>
    [LoggerMessage(
        EventId = 100,
        Level = LogLevel.Warning,
        Message = "MCP server {Server}: connection attempt {Attempt} of {Attempts} failed. "
            + "Retrying in {BackoffMs}ms.")]
    public static partial void ConnectAttemptFailed(
        ILogger logger, string server, int attempt, int attempts, double backoffMs, Exception error);

    /// <summary>A tool call failed on the connection, and the session is about to replace it.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="server">The <c>mcp:</c> id.</param>
    /// <param name="tool">The remote tool name.</param>
    /// <param name="error">What went wrong.</param>
    [LoggerMessage(
        EventId = 101,
        Level = LogLevel.Warning,
        Message = "MCP server {Server}: the call to '{Tool}' failed on the connection. "
            + "Reconnecting once and repeating it.")]
    public static partial void CallFailedReconnecting(ILogger logger, string server, string tool, Exception error);

    /// <summary>A connection would not close cleanly.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="server">The <c>mcp:</c> id.</param>
    /// <param name="error">What went wrong.</param>
    [LoggerMessage(
        EventId = 102,
        Level = LogLevel.Warning,
        Message = "MCP server {Server}: closing the connection failed. If it is a stdio server, its "
            + "child process may still be running.")]
    public static partial void CloseFailed(ILogger logger, string server, Exception error);

    /// <summary>The server withdrew tools this service is still serving ids for.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="server">The <c>mcp:</c> id.</param>
    /// <param name="dropped">The remote tool names the server stopped offering.</param>
    [LoggerMessage(
        EventId = 103,
        Level = LogLevel.Warning,
        Message = "MCP server {Server}: stopped offering {Dropped}. The served tool set is fixed at boot "
            + "and does not shrink, so calls to those ids now return an error the model can read.")]
    public static partial void ToolsDropped(ILogger logger, string server, string dropped);

    /// <summary>The server changed the arguments of a tool this service is already serving.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="server">The <c>mcp:</c> id.</param>
    /// <param name="drifted">The remote tool names whose schema no longer matches.</param>
    [LoggerMessage(
        EventId = 105,
        Level = LogLevel.Warning,
        Message = "MCP server {Server}: changed the arguments of {Drifted}. The model keeps the schema it "
            + "was given at boot, because rewriting a prompt during a live call is worse than a stale "
            + "one. Restart this service to pick the new schema up.")]
    public static partial void ToolSchemasDrifted(ILogger logger, string server, string drifted);

    /// <summary>The re-list after a <c>tools/list_changed</c> notification failed.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="server">The <c>mcp:</c> id.</param>
    /// <param name="error">What went wrong.</param>
    [LoggerMessage(
        EventId = 104,
        Level = LogLevel.Warning,
        Message = "MCP server {Server}: re-listing tools after a tools/list_changed notification failed. "
            + "The record of what it offers is now stale.")]
    public static partial void ReListFailed(ILogger logger, string server, Exception error);
}
