using Microsoft.Extensions.Logging;

namespace AgentCore.AspNetCore.DependencyInjection;

/// <summary>
/// Every line <c>AddAgentCoreAsync</c> writes while it wires the container.
/// </summary>
/// <remarks>
/// <para>
/// The methods are source-generated by <see cref="LoggerMessageAttribute"/>, so a line that nobody
/// listens to costs one level check and allocates nothing. CA1848 asks for exactly this shape
/// rather than a direct call on <see cref="ILogger"/>.
/// </para>
/// <para>
/// A line here is written once, while the process starts, and never on a turn. Startup is the one
/// moment a deployment can still be told that a default it did not choose has been chosen for it,
/// so a line that would be noise on every call is worth writing exactly here.
/// </para>
/// </remarks>
internal static partial class StartupLog
{
    /// <summary>The document named no <c>providers.audit</c>, so the in-process store was opened.</summary>
    /// <param name="logger">The factory's logger for the audit queue.</param>
    /// <remarks>
    /// A warning and not information. The default works, which is the point of having one, but the
    /// store it opens is a list in this process: it grows without a bound and it dies with the
    /// process, so a deployment that meant to write the chain of D23 somewhere durable and forgot the
    /// block would otherwise learn about it by running out of memory. The line names the fix.
    /// </remarks>
    [LoggerMessage(
        EventId = 1,
        Level = LogLevel.Warning,
        Message = "the document names no providers.audit, so the audit chain of D23 is kept in this "
            + "process. That store is not durable and it grows without a bound. Name a durable "
            + "providers.audit.kind, or write kind: memory to say this was meant.")]
    public static partial void AuditSinkDefaulted(ILogger logger);

    /// <summary>The document named no <c>providers.transcript</c>, so the in-process store was opened.</summary>
    /// <param name="logger">The factory's logger for the in-process store.</param>
    /// <remarks>
    /// The same reasoning as <see cref="AuditSinkDefaulted"/>: the default works, and it holds the
    /// words of every call in a list that grows without a bound, sweeps nothing, and dies with the
    /// process. A call cannot be resumed out of it and no retention window applies to it.
    /// </remarks>
    [LoggerMessage(
        EventId = 2,
        Level = LogLevel.Warning,
        Message = "the document names no providers.transcript, so the words of every call are kept in "
            + "this process. That store is not durable, it grows without a bound, and no retention "
            + "window applies to it. Name a durable providers.transcript.kind, or write kind: memory "
            + "to say this was meant.")]
    public static partial void TranscriptStoreDefaulted(ILogger logger);
}
