using Microsoft.Extensions.Logging;

namespace AgentCore.AspNetCore.Endpoints
{
    /// <summary>The lines the Responses path writes while it runs a turn.</summary>
    /// <remarks>Source-generated by <see cref="LoggerMessageAttribute"/>, as CA1848 asks.</remarks>
    internal static partial class ResponsesTurnLog
    {
        /// <summary>The client aborted the stream, and filing the session outran its bound.</summary>
        /// <param name="logger">The logger of the Responses path.</param>
        /// <param name="conversationId">The conversation whose session was not filed.</param>
        /// <param name="bound">How long the filing was given.</param>
        [LoggerMessage(
            EventId = 1,
            Level = LogLevel.Warning,
            Message = "the client aborted the stream of conversation '{ConversationId}', and filing its session "
                + "took longer than {Bound}, so it was abandoned. A continuation of this turn may not resume.")]
        public static partial void FilingAfterAbortTimedOut(ILogger logger, string conversationId, TimeSpan bound);
    }
}
