<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>d7549002-fd56-4ad5-b74d-3360ef14904e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AgentCore.Hosting/AgentCore.Hosting.csproj" />
    <ProjectReference Include="../AgentCore.Chat/AgentCore.Chat.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="config/example.yaml" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="config/local.yaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
