using Microsoft.Extensions.Logging;

namespace AgentCore.Application.Diagnostics;

/// <summary>
/// Every line the library writes. Three of them are the "log once" rows of section 8.7.
/// </summary>
/// <remarks>
/// <para>
/// The methods are source-generated by <see cref="LoggerMessageAttribute"/>, so a line that nobody
/// listens to costs one level check and allocates nothing. String interpolation would build the
/// message before the level check and lose every field to a flat string.
/// </para>
/// <para>
/// A line carries the call id and the turn index as fields. That is a log and not a metric, so T61
/// does not apply: Grafana Cloud bills logs by volume and the library writes once for each turn, not
/// once for each relay frame (§3.1). The unit is a frame of text and never a frame of audio: D28
/// moved the vendor boundary to text, and item 6c of section 11 keeps every audio unit — a buffer, a
/// codec, a sample rate, a playback clock — out of this solution entirely.
/// </para>
/// <para>
/// No line carries what the caller said or what the agent replied. The audit chain of D23 is the
/// record of a call, and a log is not.
/// </para>
/// </remarks>
internal static partial class Log
{
    /// <summary>Section 8.7, row two. The extractor returned an invalid object.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="callId">The id of the call.</param>
    /// <param name="turnIndex">The zero-based index of the turn that just ran.</param>
    /// <param name="reason">Why the extractor produced nothing.</param>
    /// <remarks>
    /// The slots stay unchanged and the call continues, so this is a warning and never an error.
    /// It is written once for the turn.
    /// </remarks>
    [LoggerMessage(
        EventId = 1,
        Level = LogLevel.Warning,
        Message = "The extractor of call {CallId} produced nothing for turn {TurnIndex}: {Reason} "
            + "The slots stay unchanged and the call continues.")]
    public static partial void ExtractionFailed(ILogger logger, string callId, int turnIndex, string reason);

    /// <summary>Section 8.7, row six. A tool failed four times in a row and the run threw.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="callId">The id of the call.</param>
    /// <param name="turnIndex">The zero-based index of the turn that just ran.</param>
    /// <param name="reason">The message of the fault.</param>
    /// <remarks>The turn speaks the fallback and the call stays alive, so nothing here is fatal.</remarks>
    [LoggerMessage(
        EventId = 2,
        Level = LogLevel.Error,
        Message = "A tool of call {CallId} failed four times in turn {TurnIndex}: {Reason} "
            + "The turn spoke the fallback and the call continues.")]
    public static partial void ToolBudgetSpent(ILogger logger, string callId, int turnIndex, string reason);

    /// <summary>Section 8.7, last row. The run returned quietly with no text.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="callId">The id of the call.</param>
    /// <param name="turnIndex">The zero-based index of the turn that just ran.</param>
    /// <remarks>
    /// On a voice call the silence is the failure, so the turn loop reads the reply rather than
    /// trusting the absence of an exception.
    /// </remarks>
    [LoggerMessage(
        EventId = 3,
        Level = LogLevel.Warning,
        Message = "Turn {TurnIndex} of call {CallId} returned an empty reply, so it spoke the fallback. "
            + "The run reached 40 tool rounds, or the model answered nothing.")]
    public static partial void EmptyReply(ILogger logger, string callId, int turnIndex);

    /// <summary>Section 8.7, row five. A guard threw at run time, or its rule did not parse.</summary>
    /// <param name="logger">The logger of the composition root.</param>
    /// <param name="guard">The guard name, or the rule text of an inline guard.</param>
    /// <param name="exception">The cause.</param>
    /// <remarks>
    /// <see cref="Configuration.Validation.GuardEvaluator"/> reports each distinct guard exactly
    /// once, so this line is written once for each guard and never once for each turn.
    /// </remarks>
    [LoggerMessage(
        EventId = 4,
        Level = LogLevel.Warning,
        Message = "The guard {Guard} failed. It is treated as false and the call continues.")]
    public static partial void GuardFailed(ILogger logger, string guard, Exception exception);

    /// <summary>An observer of the call refused an event, or faulted behind its own enqueue.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="callId">The id of the call.</param>
    /// <param name="kind">The wire token of the event kind.</param>
    /// <param name="exception">The cause.</param>
    /// <remarks>
    /// <para>
    /// An observer records the call and is never a part of it, so one that fails is reported and the
    /// turn goes on. When the observer is the audit sink, a lost event breaks the chain, which
    /// <c>chain_check</c> then reports.
    /// </para>
    /// <para>
    /// <see cref="Runtime.CallObserverDispatcher"/> routes EVERY observer fault through this row, not
    /// only the sink's: the telemetry and logging readings of a fact fail the same way and are worth
    /// the same line. The message names the audit sink because the text, the level, and the event id
    /// are the ones hosts already alert on and parse, and none of the three moves.
    /// </para>
    /// </remarks>
    [LoggerMessage(
        EventId = 5,
        Level = LogLevel.Error,
        Message = "The audit sink did not accept the {Kind} event of call {CallId}. "
            + "The turn continues and the chain has a gap.")]
    public static partial void AuditAppendFailed(ILogger logger, string callId, string kind, Exception exception);

    /// <summary>The moderation endpoint flagged what the caller said, so the agent refused the turn.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="callId">The id of the call.</param>
    /// <param name="turnIndex">The zero-based index of the turn.</param>
    /// <param name="categories">The categories the endpoint flagged, comma-separated, in its order.</param>
    /// <remarks>
    /// The words the caller spoke are NOT logged. They are the text that was flagged, so a log line
    /// carrying them would copy the content out of the audit chain and into a log store that D23 does
    /// not protect. The audit chain records the categories, and this line reports the same fact where
    /// an operator watches.
    /// </remarks>
    [LoggerMessage(
        EventId = 6,
        Level = LogLevel.Warning,
        Message = "Moderation flagged turn {TurnIndex} of call {CallId} for {Categories}, "
            + "so the agent refused it and spoke the refusal line.")]
    public static partial void PromptRefused(ILogger logger, string callId, int turnIndex, string categories);

    /// <summary>The moderation endpoint did not answer, so the turn ran unchecked.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="callId">The id of the call.</param>
    /// <param name="turnIndex">The zero-based index of the turn.</param>
    /// <param name="reason">What went wrong.</param>
    /// <remarks>
    /// Moderation fails OPEN, and that is deliberate: a vendor outage must not refuse every caller on
    /// a support line. The turn goes on, and this line plus the <c>unavailable</c> metric outcome are
    /// the only record that it went unchecked. It is a warning and not an error, because a vendor
    /// that did not answer is not a defect in this library.
    /// </remarks>
    [LoggerMessage(
        EventId = 7,
        Level = LogLevel.Warning,
        Message = "Moderation did not answer for turn {TurnIndex} of call {CallId} ({Reason}). "
            + "The turn ran unchecked, because moderation fails open.")]
    public static partial void ModerationUnavailable(ILogger logger, string callId, int turnIndex, string reason);

    /// <summary>The audit queue had no room, so the event was dropped.</summary>
    /// <param name="logger">The logger of the queue.</param>
    /// <param name="callId">The id of the call the dropped event belongs to.</param>
    /// <param name="sequence">The per-call sequence number of the dropped event.</param>
    /// <remarks>
    /// <para>
    /// An implementation of <see cref="Ports.IAuditSinkPort"/> does not throw for a full queue and it
    /// does not block. Audit is a record of the call and never a part of it, so a store that cannot
    /// keep up drops and reports rather than slowing the caller down, and this line is the report.
    /// </para>
    /// <para>
    /// A dropped event is a gap in the chain, which <c>chain_check</c> then reports. It is an error
    /// and not a warning for that reason: the queue of <see cref="Audit.QueuedAuditSink"/> is sized to
    /// absorb the p99 of section 7, so one of these lines means the store has been unreachable or slow
    /// for long enough to matter, and an operator alerts on it.
    /// </para>
    /// </remarks>
    [LoggerMessage(
        EventId = 8,
        Level = LogLevel.Error,
        Message = "The audit queue was full, so event {Sequence} of call {CallId} was dropped. "
            + "The call continues and the chain has a gap.")]
    public static partial void AuditQueueFull(ILogger logger, string callId, long sequence);
}
