using Microsoft.Extensions.Logging;

namespace AgentCore.Application.Diagnostics;

/// <summary>
/// Every line the library writes. Three of them are the "log once" rows of section 8.7.
/// </summary>
/// <remarks>
/// <para>
/// The methods are source-generated by <see cref="LoggerMessageAttribute"/>, so a line that nobody
/// listens to costs one level check and allocates nothing. String interpolation would build the
/// message before the level check and lose every field to a flat string.
/// </para>
/// <para>
/// A line carries the call id and the turn index as fields. That is a log and not a metric, so T61
/// does not apply: Grafana Cloud bills logs by volume and the library writes once for each turn, not
/// once for each audio frame (§3.1).
/// </para>
/// <para>
/// No line carries what the caller said or what the agent replied. The audit chain of D23 is the
/// record of a call, and a log is not.
/// </para>
/// </remarks>
internal static partial class Log
{
    /// <summary>Section 8.7, row two. The extractor returned an invalid object.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="callId">The id of the call.</param>
    /// <param name="turnIndex">The zero-based index of the turn that just ran.</param>
    /// <param name="reason">Why the extractor produced nothing.</param>
    /// <remarks>
    /// The slots stay unchanged and the call continues, so this is a warning and never an error.
    /// It is written once for the turn.
    /// </remarks>
    [LoggerMessage(
        EventId = 1,
        Level = LogLevel.Warning,
        Message = "The extractor of call {CallId} produced nothing for turn {TurnIndex}: {Reason} "
            + "The slots stay unchanged and the call continues.")]
    public static partial void ExtractionFailed(ILogger logger, string callId, int turnIndex, string reason);

    /// <summary>Section 8.7, row six. A tool failed four times in a row and the run threw.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="callId">The id of the call.</param>
    /// <param name="turnIndex">The zero-based index of the turn that just ran.</param>
    /// <param name="reason">The message of the fault.</param>
    /// <remarks>The turn speaks the fallback and the call stays alive, so nothing here is fatal.</remarks>
    [LoggerMessage(
        EventId = 2,
        Level = LogLevel.Error,
        Message = "A tool of call {CallId} failed four times in turn {TurnIndex}: {Reason} "
            + "The turn spoke the fallback and the call continues.")]
    public static partial void ToolBudgetSpent(ILogger logger, string callId, int turnIndex, string reason);

    /// <summary>Section 8.7, last row. The run returned quietly with no text.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="callId">The id of the call.</param>
    /// <param name="turnIndex">The zero-based index of the turn that just ran.</param>
    /// <remarks>
    /// On a voice call the silence is the failure, so the turn loop reads the reply rather than
    /// trusting the absence of an exception.
    /// </remarks>
    [LoggerMessage(
        EventId = 3,
        Level = LogLevel.Warning,
        Message = "Turn {TurnIndex} of call {CallId} returned an empty reply, so it spoke the fallback. "
            + "The run reached 40 tool rounds, or the model answered nothing.")]
    public static partial void EmptyReply(ILogger logger, string callId, int turnIndex);

    /// <summary>Section 8.7, row five. A guard threw at run time, or its rule did not parse.</summary>
    /// <param name="logger">The logger of the composition root.</param>
    /// <param name="guard">The guard name, or the rule text of an inline guard.</param>
    /// <param name="exception">The cause.</param>
    /// <remarks>
    /// <see cref="Configuration.Validation.GuardEvaluator"/> reports each distinct guard exactly
    /// once, so this line is written once for each guard and never once for each turn.
    /// </remarks>
    [LoggerMessage(
        EventId = 4,
        Level = LogLevel.Warning,
        Message = "The guard {Guard} failed. It is treated as false and the call continues.")]
    public static partial void GuardFailed(ILogger logger, string guard, Exception exception);

    /// <summary>The audit sink refused an event, or faulted behind the enqueue.</summary>
    /// <param name="logger">The logger of the session.</param>
    /// <param name="callId">The id of the call.</param>
    /// <param name="kind">The wire token of the event kind.</param>
    /// <param name="exception">The cause.</param>
    /// <remarks>
    /// Audit is a record of the call and never a part of it, so a sink that fails is reported and the
    /// turn goes on. A lost event breaks the chain, which <c>chain_check</c> then reports.
    /// </remarks>
    [LoggerMessage(
        EventId = 5,
        Level = LogLevel.Error,
        Message = "The audit sink did not accept the {Kind} event of call {CallId}. "
            + "The turn continues and the chain has a gap.")]
    public static partial void AuditAppendFailed(ILogger logger, string callId, string kind, Exception exception);
}
